#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-kcc
Version  : 0.0.9
Release  : 21
URL      : https://files.pythonhosted.org/packages/7e/c3/f9ba13362899209242078bbf24c7d8e62baf90ae23d9a199429e07a78d60/kcc-0.0.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/7e/c3/f9ba13362899209242078bbf24c7d8e62baf90ae23d9a199429e07a78d60/kcc-0.0.9.tar.gz
Summary  : Check kernel config for security issues
Group    : Development/Tools
License  : GPL-3.0
Requires: pypi-kcc-bin = %{version}-%{release}
Requires: pypi-kcc-python = %{version}-%{release}
Requires: pypi-kcc-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
===========================

%package bin
Summary: bin components for the pypi-kcc package.
Group: Binaries

%description bin
bin components for the pypi-kcc package.


%package python
Summary: python components for the pypi-kcc package.
Group: Default
Requires: pypi-kcc-python3 = %{version}-%{release}

%description python
python components for the pypi-kcc package.


%package python3
Summary: python3 components for the pypi-kcc package.
Group: Default
Requires: python3-core
Provides: pypi(kcc)

%description python3
python3 components for the pypi-kcc package.


%prep
%setup -q -n kcc-0.0.9
cd %{_builddir}/kcc-0.0.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649776803
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kcc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
